config/routes.rb
ContractManager::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :obligations

  resources :one_time_obligations

  resources :reoccuring_obligations

  resources :agreements

  resources :obligation_rules

end

app/models/obligation.rb
class Obligation < ActiveRecord::Base
  attr_accessible :amount, :date_met, :description, :due_date, :invoice_number, :met, :monetary, :name
  belongs_to :one_time_obligation
  belongs_to :reoccuring_obligation
end

app/controllers/obligations_controller.rb
class ObligationsController < ApplicationController
  # GET /obligations
  # GET /obligations.json
  def index
    @obligations = Obligation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @obligations }
    end
  end

  # GET /obligations/1
  # GET /obligations/1.json
  def show
    @obligation = Obligation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @obligation }
    end
  end

  # GET /obligations/new
  # GET /obligations/new.json
  def new
    @obligation = Obligation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @obligation }
    end
  end

  # GET /obligations/1/edit
  def edit
    @obligation = Obligation.find(params[:id])
  end

  # POST /obligations
  # POST /obligations.json
  def create
    @obligation = Obligation.new(params[:obligation])

    respond_to do |format|
      if @obligation.save
        format.html { redirect_to @obligation, notice: 'Obligation was successfully created.' }
        format.json { render json: @obligation, status: :created, location: @obligation }
      else
        format.html { render action: "new" }
        format.json { render json: @obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /obligations/1
  # PUT /obligations/1.json
  def update
    @obligation = Obligation.find(params[:id])

    respond_to do |format|
      if @obligation.update_attributes(params[:obligation])
        format.html { redirect_to @obligation, notice: 'Obligation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obligations/1
  # DELETE /obligations/1.json
  def destroy
    @obligation = Obligation.find(params[:id])
    @obligation.destroy

    respond_to do |format|
      format.html { redirect_to obligations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/obligations_helper.rb
module ObligationsHelper
end

app/views/obligations/_form.html.erb
<%= form_for(@obligation) do |f| %>
  <% if @obligation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@obligation.errors.count, "error") %> prohibited this obligation from being saved:</h2>

      <ul>
      <% @obligation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :met %><br />
    <%= f.check_box :met %>
  </div>
  <div class="field">
    <%= f.label :date_met %><br />
    <%= f.date_select :date_met %>
  </div>
  <div class="field">
    <%= f.label :monetary %><br />
    <%= f.check_box :monetary %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :invoice_number %><br />
    <%= f.text_field :invoice_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/obligations/edit.html.erb
<h1>Editing obligation</h1>

<%= render 'form' %>

<%= link_to 'Show', @obligation %> |
<%= link_to 'Back', obligations_path %>

app/views/obligations/index.html.erb
<h1>Listing obligations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Due date</th>
    <th>Met</th>
    <th>Date met</th>
    <th>Monetary</th>
    <th>Amount</th>
    <th>Invoice number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @obligations.each do |obligation| %>
  <tr>
    <td><%= obligation.name %></td>
    <td><%= obligation.description %></td>
    <td><%= obligation.due_date %></td>
    <td><%= obligation.met %></td>
    <td><%= obligation.date_met %></td>
    <td><%= obligation.monetary %></td>
    <td><%= obligation.amount %></td>
    <td><%= obligation.invoice_number %></td>
    <td><%= link_to 'Show', obligation %></td>
    <td><%= link_to 'Edit', edit_obligation_path(obligation) %></td>
    <td><%= link_to 'Destroy', obligation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Obligation', new_obligation_path %>

app/views/obligations/new.html.erb
<h1>New obligation</h1>

<%= render 'form' %>

<%= link_to 'Back', obligations_path %>

app/views/obligations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @obligation.name %>
</p>

<p>
  <b>Description:</b>
  <%= @obligation.description %>
</p>

<p>
  <b>Due date:</b>
  <%= @obligation.due_date %>
</p>

<p>
  <b>Met:</b>
  <%= @obligation.met %>
</p>

<p>
  <b>Date met:</b>
  <%= @obligation.date_met %>
</p>

<p>
  <b>Monetary:</b>
  <%= @obligation.monetary %>
</p>

<p>
  <b>Amount:</b>
  <%= @obligation.amount %>
</p>

<p>
  <b>Invoice number:</b>
  <%= @obligation.invoice_number %>
</p>


<%= link_to 'Edit', edit_obligation_path(@obligation) %> |
<%= link_to 'Back', obligations_path %>