config/routes.rb
ContractManager::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :obligations

  resources :one_time_obligations

  resources :reoccuring_obligations

  resources :agreements

  resources :obligation_rules

end

app/models/agreement.rb
class Agreement < ActiveRecord::Base
  attr_accessible :contract_manager, :ipp_agreement_guid, :name, :set_up_complete
  has_many :obligation_rules
end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
  # GET /agreements
  # GET /agreements.json
  def index
    @agreements = Agreement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agreements }
    end
  end

  # GET /agreements/1
  # GET /agreements/1.json
  def show
    @agreement = Agreement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agreement }
    end
  end

  # GET /agreements/new
  # GET /agreements/new.json
  def new
    @agreement = Agreement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agreement }
    end
  end

  # GET /agreements/1/edit
  def edit
    @agreement = Agreement.find(params[:id])
  end

  # POST /agreements
  # POST /agreements.json
  def create
    @agreement = Agreement.new(params[:agreement])

    respond_to do |format|
      if @agreement.save
        format.html { redirect_to @agreement, notice: 'Agreement was successfully created.' }
        format.json { render json: @agreement, status: :created, location: @agreement }
      else
        format.html { render action: "new" }
        format.json { render json: @agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agreements/1
  # PUT /agreements/1.json
  def update
    @agreement = Agreement.find(params[:id])

    respond_to do |format|
      if @agreement.update_attributes(params[:agreement])
        format.html { redirect_to @agreement, notice: 'Agreement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agreements/1
  # DELETE /agreements/1.json
  def destroy
    @agreement = Agreement.find(params[:id])
    @agreement.destroy

    respond_to do |format|
      format.html { redirect_to agreements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/views/agreements/_form.html.erb
<%= form_for(@agreement) do |f| %>
  <% if @agreement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agreement.errors.count, "error") %> prohibited this agreement from being saved:</h2>

      <ul>
      <% @agreement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ipp_agreement_guid %><br />
    <%= f.text_field :ipp_agreement_guid %>
  </div>
  <div class="field">
    <%= f.label :contract_manager %><br />
    <%= f.text_field :contract_manager %>
  </div>
  <div class="field">
    <%= f.label :set_up_complete %><br />
    <%= f.check_box :set_up_complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agreements/edit.html.erb
<h1>Editing agreement</h1>

<%= render 'form' %>

<%= link_to 'Show', @agreement %> |
<%= link_to 'Back', agreements_path %>

app/views/agreements/index.html.erb
<h1>Listing agreements</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Ipp agreement guid</th>
    <th>Contract manager</th>
    <th>Set up complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agreements.each do |agreement| %>
  <tr>
    <td><%= agreement.name %></td>
    <td><%= agreement.ipp_agreement_guid %></td>
    <td><%= agreement.contract_manager %></td>
    <td><%= agreement.set_up_complete %></td>
    <td><%= link_to 'Show', agreement %></td>
    <td><%= link_to 'Edit', edit_agreement_path(agreement) %></td>
    <td><%= link_to 'Destroy', agreement, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agreement', new_agreement_path %>

app/views/agreements/new.html.erb
<h1>New agreement</h1>

<%= render 'form' %>

<%= link_to 'Back', agreements_path %>

app/views/agreements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @agreement.name %>
</p>

<p>
  <b>Ipp agreement guid:</b>
  <%= @agreement.ipp_agreement_guid %>
</p>

<p>
  <b>Contract manager:</b>
  <%= @agreement.contract_manager %>
</p>

<p>
  <b>Set up complete:</b>
  <%= @agreement.set_up_complete %>
</p>


<%= link_to 'Edit', edit_agreement_path(@agreement) %> |
<%= link_to 'Back', agreements_path %>