config/routes.rb
ContractManager::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :obligations

  resources :one_time_obligations

  resources :reoccuring_obligations

  resources :agreements

  resources :obligation_rules

end

app/models/reoccuring_obligation.rb
class ReoccuringObligation < ActiveRecord::Base
  attr_accessible :amount, :duration, :duration_period, :end_date, :frequency, :frequency_period, :is_dependent, :monetary, :name, :obligation_rule_id, :start_date
  has_many :obligations
  belongs_to :obligation_rule
end

app/controllers/reoccuring_obligations_controller.rb
class ReoccuringObligationsController < ApplicationController
  # GET /reoccuring_obligations
  # GET /reoccuring_obligations.json
  def index
    @reoccuring_obligations = ReoccuringObligation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reoccuring_obligations }
    end
  end

  # GET /reoccuring_obligations/1
  # GET /reoccuring_obligations/1.json
  def show
    @reoccuring_obligation = ReoccuringObligation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reoccuring_obligation }
    end
  end

  # GET /reoccuring_obligations/new
  # GET /reoccuring_obligations/new.json
  def new
    @reoccuring_obligation = ReoccuringObligation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reoccuring_obligation }
    end
  end

  # GET /reoccuring_obligations/1/edit
  def edit
    @reoccuring_obligation = ReoccuringObligation.find(params[:id])
  end

  # POST /reoccuring_obligations
  # POST /reoccuring_obligations.json
  def create
    @reoccuring_obligation = ReoccuringObligation.new(params[:reoccuring_obligation])

    respond_to do |format|
      if @reoccuring_obligation.save
        format.html { redirect_to @reoccuring_obligation, notice: 'Reoccuring obligation was successfully created.' }
        format.json { render json: @reoccuring_obligation, status: :created, location: @reoccuring_obligation }
      else
        format.html { render action: "new" }
        format.json { render json: @reoccuring_obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reoccuring_obligations/1
  # PUT /reoccuring_obligations/1.json
  def update
    @reoccuring_obligation = ReoccuringObligation.find(params[:id])

    respond_to do |format|
      if @reoccuring_obligation.update_attributes(params[:reoccuring_obligation])
        format.html { redirect_to @reoccuring_obligation, notice: 'Reoccuring obligation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reoccuring_obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reoccuring_obligations/1
  # DELETE /reoccuring_obligations/1.json
  def destroy
    @reoccuring_obligation = ReoccuringObligation.find(params[:id])
    @reoccuring_obligation.destroy

    respond_to do |format|
      format.html { redirect_to reoccuring_obligations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reoccuring_obligations_helper.rb
module ReoccuringObligationsHelper
end

app/views/reoccuring_obligations/_form.html.erb
<%= form_for(@reoccuring_obligation) do |f| %>
  <% if @reoccuring_obligation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reoccuring_obligation.errors.count, "error") %> prohibited this reoccuring_obligation from being saved:</h2>

      <ul>
      <% @reoccuring_obligation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :obligation_rule_id %><br />
    <%= f.number_field :obligation_rule_id %>
  </div>
  <div class="field">
    <%= f.label :frequency %><br />
    <%= f.number_field :frequency %>
  </div>
  <div class="field">
    <%= f.label :frequency_period %><br />
    <%= f.text_field :frequency_period %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :duration_period %><br />
    <%= f.text_field :duration_period %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :is_dependent %><br />
    <%= f.check_box :is_dependent %>
  </div>
  <div class="field">
    <%= f.label :monetary %><br />
    <%= f.check_box :monetary %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reoccuring_obligations/edit.html.erb
<h1>Editing reoccuring_obligation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reoccuring_obligation %> |
<%= link_to 'Back', reoccuring_obligations_path %>

app/views/reoccuring_obligations/index.html.erb
<h1>Listing reoccuring_obligations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Obligation rule</th>
    <th>Frequency</th>
    <th>Frequency period</th>
    <th>Duration</th>
    <th>Duration period</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Is dependent</th>
    <th>Monetary</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reoccuring_obligations.each do |reoccuring_obligation| %>
  <tr>
    <td><%= reoccuring_obligation.name %></td>
    <td><%= reoccuring_obligation.obligation_rule_id %></td>
    <td><%= reoccuring_obligation.frequency %></td>
    <td><%= reoccuring_obligation.frequency_period %></td>
    <td><%= reoccuring_obligation.duration %></td>
    <td><%= reoccuring_obligation.duration_period %></td>
    <td><%= reoccuring_obligation.start_date %></td>
    <td><%= reoccuring_obligation.end_date %></td>
    <td><%= reoccuring_obligation.is_dependent %></td>
    <td><%= reoccuring_obligation.monetary %></td>
    <td><%= reoccuring_obligation.amount %></td>
    <td><%= link_to 'Show', reoccuring_obligation %></td>
    <td><%= link_to 'Edit', edit_reoccuring_obligation_path(reoccuring_obligation) %></td>
    <td><%= link_to 'Destroy', reoccuring_obligation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reoccuring obligation', new_reoccuring_obligation_path %>

app/views/reoccuring_obligations/new.html.erb
<h1>New reoccuring_obligation</h1>

<%= render 'form' %>

<%= link_to 'Back', reoccuring_obligations_path %>

app/views/reoccuring_obligations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reoccuring_obligation.name %>
</p>

<p>
  <b>Obligation rule:</b>
  <%= @reoccuring_obligation.obligation_rule_id %>
</p>

<p>
  <b>Frequency:</b>
  <%= @reoccuring_obligation.frequency %>
</p>

<p>
  <b>Frequency period:</b>
  <%= @reoccuring_obligation.frequency_period %>
</p>

<p>
  <b>Duration:</b>
  <%= @reoccuring_obligation.duration %>
</p>

<p>
  <b>Duration period:</b>
  <%= @reoccuring_obligation.duration_period %>
</p>

<p>
  <b>Start date:</b>
  <%= @reoccuring_obligation.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @reoccuring_obligation.end_date %>
</p>

<p>
  <b>Is dependent:</b>
  <%= @reoccuring_obligation.is_dependent %>
</p>

<p>
  <b>Monetary:</b>
  <%= @reoccuring_obligation.monetary %>
</p>

<p>
  <b>Amount:</b>
  <%= @reoccuring_obligation.amount %>
</p>


<%= link_to 'Edit', edit_reoccuring_obligation_path(@reoccuring_obligation) %> |
<%= link_to 'Back', reoccuring_obligations_path %>