config/routes.rb
ContractManager::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :obligations

  resources :one_time_obligations

  resources :reoccuring_obligations

  resources :agreements

  resources :obligation_rules

end

app/models/one_time_obligation.rb
class OneTimeObligation < ActiveRecord::Base
  attr_accessible :amount, :due_date, :is_dependent, :monetary, :name, :obligation_rule_id
  has_many :obligations
  belongs_to :obligation_rule
end

app/controllers/one_time_obligations_controller.rb
class OneTimeObligationsController < ApplicationController
  # GET /one_time_obligations
  # GET /one_time_obligations.json
  def index
    @one_time_obligations = OneTimeObligation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @one_time_obligations }
    end
  end

  # GET /one_time_obligations/1
  # GET /one_time_obligations/1.json
  def show
    @one_time_obligation = OneTimeObligation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @one_time_obligation }
    end
  end

  # GET /one_time_obligations/new
  # GET /one_time_obligations/new.json
  def new
    @one_time_obligation = OneTimeObligation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @one_time_obligation }
    end
  end

  # GET /one_time_obligations/1/edit
  def edit
    @one_time_obligation = OneTimeObligation.find(params[:id])
  end

  # POST /one_time_obligations
  # POST /one_time_obligations.json
  def create
    @one_time_obligation = OneTimeObligation.new(params[:one_time_obligation])

    respond_to do |format|
      if @one_time_obligation.save
        format.html { redirect_to @one_time_obligation, notice: 'One time obligation was successfully created.' }
        format.json { render json: @one_time_obligation, status: :created, location: @one_time_obligation }
      else
        format.html { render action: "new" }
        format.json { render json: @one_time_obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /one_time_obligations/1
  # PUT /one_time_obligations/1.json
  def update
    @one_time_obligation = OneTimeObligation.find(params[:id])

    respond_to do |format|
      if @one_time_obligation.update_attributes(params[:one_time_obligation])
        format.html { redirect_to @one_time_obligation, notice: 'One time obligation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @one_time_obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /one_time_obligations/1
  # DELETE /one_time_obligations/1.json
  def destroy
    @one_time_obligation = OneTimeObligation.find(params[:id])
    @one_time_obligation.destroy

    respond_to do |format|
      format.html { redirect_to one_time_obligations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/one_time_obligations_helper.rb
module OneTimeObligationsHelper
end

app/views/one_time_obligations/_form.html.erb
<%= form_for(@one_time_obligation) do |f| %>
  <% if @one_time_obligation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@one_time_obligation.errors.count, "error") %> prohibited this one_time_obligation from being saved:</h2>

      <ul>
      <% @one_time_obligation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :obligation_rule_id %><br />
    <%= f.number_field :obligation_rule_id %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :is_dependent %><br />
    <%= f.check_box :is_dependent %>
  </div>
  <div class="field">
    <%= f.label :monetary %><br />
    <%= f.check_box :monetary %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/one_time_obligations/edit.html.erb
<h1>Editing one_time_obligation</h1>

<%= render 'form' %>

<%= link_to 'Show', @one_time_obligation %> |
<%= link_to 'Back', one_time_obligations_path %>

app/views/one_time_obligations/index.html.erb
<h1>Listing one_time_obligations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Obligation rule</th>
    <th>Due date</th>
    <th>Is dependent</th>
    <th>Monetary</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @one_time_obligations.each do |one_time_obligation| %>
  <tr>
    <td><%= one_time_obligation.name %></td>
    <td><%= one_time_obligation.obligation_rule_id %></td>
    <td><%= one_time_obligation.due_date %></td>
    <td><%= one_time_obligation.is_dependent %></td>
    <td><%= one_time_obligation.monetary %></td>
    <td><%= one_time_obligation.amount %></td>
    <td><%= link_to 'Show', one_time_obligation %></td>
    <td><%= link_to 'Edit', edit_one_time_obligation_path(one_time_obligation) %></td>
    <td><%= link_to 'Destroy', one_time_obligation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New One time obligation', new_one_time_obligation_path %>

app/views/one_time_obligations/new.html.erb
<h1>New one_time_obligation</h1>

<%= render 'form' %>

<%= link_to 'Back', one_time_obligations_path %>

app/views/one_time_obligations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @one_time_obligation.name %>
</p>

<p>
  <b>Obligation rule:</b>
  <%= @one_time_obligation.obligation_rule_id %>
</p>

<p>
  <b>Due date:</b>
  <%= @one_time_obligation.due_date %>
</p>

<p>
  <b>Is dependent:</b>
  <%= @one_time_obligation.is_dependent %>
</p>

<p>
  <b>Monetary:</b>
  <%= @one_time_obligation.monetary %>
</p>

<p>
  <b>Amount:</b>
  <%= @one_time_obligation.amount %>
</p>


<%= link_to 'Edit', edit_one_time_obligation_path(@one_time_obligation) %> |
<%= link_to 'Back', one_time_obligations_path %>